### ISSUE TITLE
mean init <projectname>

### ISSUE THREAD

**Issue by edisontkp** [linnovate/mean-cli#105]
Installation of mean should not be done as root! bailing out

/usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
RUNNING AS ROOT

How to solve this problem? Thanks

**Comment by liorkesos** [comment]
Yes.
This is not a bug but mean should not be installed as root because it
introdcues a security problem in production and can mess up you .npm
directory.

On Wed, Apr 15, 2015 at 7:59 PM, edisontkp <notifications@github.com> wrote:

> Installation of mean should not be done as root! bailing out
>
>
> /usr/local/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
> throw e;
> ^
> RUNNING AS ROOT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean-cli/issues/105>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos
